name: ApiGen

on:
  push:
    branches:
      - master

jobs:
  apigen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ApiGen Docs
      uses: varunsridharan/action-apigen@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
